### ISSUE TITLE
source repository out of date

### ISSUE THREAD

**Issue by quozl** [sugarlabs/Time-Line#4]
There is a `time_line-4.xo` available from activities.sugarlabs.org yet this repository shows current version of 3.

**Comment by H1manshu21** [comment]
Should I upload time line version 4 to resolve this issue or any?

**Comment by H1manshu21** [comment]
Updated the activity.info of version 4 :+1:

**Comment by rhl-bthr** [comment]
Fixed in 61bd2a4
